### ISSUE TITLE
Signature Errors/Missing Private Key

### ISSUE THREAD

**Issue by Seathre** [Pursec/Pylon-Bodger#1]
Looks like you copied the addon signature (GES Pylon Bodger.pbo.pylon bodger.bisign) into the keys folder where your public key (pylon bodger.bikey) should be. This is causing signature errors on servers which allow the mod.

You should have a public key in the same directory you saved your private key to, which was required before signing the mod. Your private key (pylon bodger.biprivatekey) should always remain safely in your hands and not be shared.

https://community.bistudio.com/wiki/Arma_3:_Creating_an_Addon#Keys_and_Signatures
https://community.bistudio.com/wiki/Arma_3:_Creating_an_Addon#Mod_Folder_Structure

**Comment by Pursec** [comment]
Republished the mod with the proper public key. Honestly dont know why I did that in the first place and im going to pin it on sleep deprived development at the time. Thank you for letting me know to get this fixed!
